//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elbitin.Applications.RAAS.RAASClient.RAASClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elbitin.Applications.RAAS.RAASClient.RAASClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About RAAS Client.
        /// </summary>
        internal static string AboutForm_AboutFormTitle {
            get {
                return ResourceManager.GetString("AboutForm_AboutFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2025 Elbitin.
        /// </summary>
        internal static string AboutForm_CopyrightNoticeLabel {
            get {
                return ResourceManager.GetString("AboutForm_CopyrightNoticeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AboutForm_OkButton {
            get {
                return ResourceManager.GetString("AboutForm_OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAAS Client.
        /// </summary>
        internal static string AboutForm_ProgramNameLabel {
            get {
                return ResourceManager.GetString("AboutForm_ProgramNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version..
        /// </summary>
        internal static string AboutForm_RightsLabel {
            get {
                return ResourceManager.GetString("AboutForm_RightsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string AboutForm_VersionLabel {
            get {
                return ResourceManager.GetString("AboutForm_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to log off {0}.
        /// </summary>
        internal static string Actions_LogOffFailedMessage {
            get {
                return ResourceManager.GetString("Actions_LogOffFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reboot {0}.
        /// </summary>
        internal static string Actions_RebootFailedMessage {
            get {
                return ResourceManager.GetString("Actions_RebootFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update shortcuts {0}.
        /// </summary>
        internal static string Actions_UpdateShortcutsFailedMessage {
            get {
                return ResourceManager.GetString("Actions_UpdateShortcutsFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAAS Server Configuration.
        /// </summary>
        internal static string ConextMenu_RAASServerConfigurationItem {
            get {
                return ResourceManager.GetString("ConextMenu_RAASServerConfigurationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop.
        /// </summary>
        internal static string ConextMenu_RemoteDesktopItem {
            get {
                return ResourceManager.GetString("ConextMenu_RemoteDesktopItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Connect {
            get {
                object obj = ResourceManager.GetObject("Connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ContextMenu_AboutItem {
            get {
                return ResourceManager.GetString("ContextMenu_AboutItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available.
        /// </summary>
        internal static string ContextMenu_AvailableSubString {
            get {
                return ResourceManager.GetString("ContextMenu_AvailableSubString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  connected.
        /// </summary>
        internal static string ContextMenu_ConnectedSubString {
            get {
                return ResourceManager.GetString("ContextMenu_ConnectedSubString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string ContextMenu_ConnectItem {
            get {
                return ResourceManager.GetString("ContextMenu_ConnectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string ContextMenu_DisconnectItem {
            get {
                return ResourceManager.GetString("ContextMenu_DisconnectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ContextMenu_ExitItem {
            get {
                return ResourceManager.GetString("ContextMenu_ExitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help (pdf).
        /// </summary>
        internal static string ContextMenu_HelpItem {
            get {
                return ResourceManager.GetString("ContextMenu_HelpItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        internal static string ContextMenu_LogoffItem {
            get {
                return ResourceManager.GetString("ContextMenu_LogoffItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offline.
        /// </summary>
        internal static string ContextMenu_OfflineSubString {
            get {
                return ResourceManager.GetString("ContextMenu_OfflineSubString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        internal static string ContextMenu_RebootItem {
            get {
                return ResourceManager.GetString("ContextMenu_RebootItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        internal static string ContextMenu_ReconnectItem {
            get {
                return ResourceManager.GetString("ContextMenu_ReconnectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string ContextMenu_ServerItem {
            get {
                return ResourceManager.GetString("ContextMenu_ServerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Shortcuts.
        /// </summary>
        internal static string ContextMenu_UpdateShortcutstItem {
            get {
                return ResourceManager.GetString("ContextMenu_UpdateShortcutstItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Disconnect {
            get {
                object obj = ResourceManager.GetObject("Disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logout {
            get {
                object obj = ResourceManager.GetObject("Logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        internal static string Notification_ConnectedMessage {
            get {
                return ResourceManager.GetString("Notification_ConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed connecting to {0}.
        /// </summary>
        internal static string Notification_ConnectionFailedMessage {
            get {
                return ResourceManager.GetString("Notification_ConnectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from {0}.
        /// </summary>
        internal static string Notification_DisconnectedMessage {
            get {
                return ResourceManager.GetString("Notification_DisconnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAAS Client error.
        /// </summary>
        internal static string Program_ErrorMessageTitle {
            get {
                return ResourceManager.GetString("Program_ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RAASIcon {
            get {
                object obj = ResourceManager.GetObject("RAASIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rdesktop {
            get {
                object obj = ResourceManager.GetObject("Rdesktop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reboot {
            get {
                object obj = ResourceManager.GetObject("Reboot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reconnect {
            get {
                object obj = ResourceManager.GetObject("Reconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Serverconfig {
            get {
                object obj = ResourceManager.GetObject("Serverconfig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load server settings.
        /// </summary>
        internal static string ServerSettings_LoadFailedMessage {
            get {
                return ResourceManager.GetString("ServerSettings_LoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shortcuts {
            get {
                object obj = ResourceManager.GetObject("Shortcuts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
