@echo off
call ..\setversions.bat
copy RAASClient_x64_en-US.msi RAASClient_%RAASClientVersion%_x64.msi
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_sv-SE.msi" -out sv-se.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_af.msi" -out af.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_am.msi" -out am.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ar.msi" -out ar.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_az.msi" -out az.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_be.msi" -out be.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_bg.msi" -out bg.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_bs.msi" -out bs.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ca.msi" -out ca.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_co.msi" -out co.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_cs.msi" -out cs.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_cy.msi" -out cy.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_da.msi" -out da.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_de.msi" -out de.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_el.msi" -out el.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_en.msi" -out en.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_eo.msi" -out eo.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_es.msi" -out es.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_et.msi" -out et.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_eu.msi" -out eu.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_fa.msi" -out fa.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_fi.msi" -out fi.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_fr.msi" -out fr.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ga.msi" -out ga.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_gd.msi" -out gd.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_gl.msi" -out gl.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_gu.msi" -out gu.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ha.msi" -out ha.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_haw.msi" -out haw.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_hi.msi" -out hi.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_hr.msi" -out hr.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ht.msi" -out ht.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_hu.msi" -out hu.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_hy.msi" -out hy.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_id.msi" -out id.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ig.msi" -out ig.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_is.msi" -out is.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_it.msi" -out it.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_iw.msi" -out iw.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ja.msi" -out ja.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_jw.msi" -out jw.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ka.msi" -out ka.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_kk.msi" -out kk.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_km.msi" -out km.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_kn.msi" -out kn.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ko.msi" -out ko.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ku.msi" -out ku.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ky.msi" -out ky.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_la.msi" -out la.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_lo.msi" -out lo.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_lt.msi" -out lt.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_lv.msi" -out lv.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_mg.msi" -out mg.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_mi.msi" -out mi.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_mk.msi" -out mk.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ml.msi" -out ml.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_mn.msi" -out mn.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_mr.msi" -out mr.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ms.msi" -out ms.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_mt.msi" -out mt.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ne.msi" -out ne.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_nl.msi" -out nl.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_no.msi" -out no.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_pa.msi" -out pa.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_pl.msi" -out pl.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ps.msi" -out ps.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_pt-BR.msi" -out pt-BR.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_pt-PT.msi" -out pt-PT.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ro.msi" -out ro.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ru.msi" -out ru.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_sd.msi" -out sd.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_si.msi" -out si.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_sk.msi" -out sk.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_sl.msi" -out sl.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_sn.msi" -out sn.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_so.msi" -out so.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_sq.msi" -out sq.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_sr.msi" -out sr.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_su.msi" -out su.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_sw.msi" -out sw.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ta.msi" -out ta.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_te.msi" -out te.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_tg.msi" -out tg.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_th.msi" -out th.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_tk.msi" -out tk.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_tl.msi" -out tl.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_tr.msi" -out tr.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_tt.msi" -out tt.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ug.msi" -out ug.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_uk.msi" -out uk.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_ur.msi" -out ur.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_uz.msi" -out uz.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_vi.msi" -out vi.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_xh.msi" -out xh.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_yi.msi" -out yi.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_yo.msi" -out yo.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_zh-CN.msi" -out zh-CN.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_zh-TW.msi" -out zh-TW.mst
wix msi transform -t language "RAASClient_%RAASClientVersion%_x64.msi" "RAASClient_x64_zu.msi" -out zu.mst
cscript ..\scripts\WiSubStg.vbs "RAASClient_%RAASClientVersion%_x64.msi" sv-se.mst 1053
cscript ..\scripts\WiLangId.vbs "RAASClient_%RAASClientVersion%_x64.msi" Package 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1069, 1071, 1077, 1078, 1079, 1081, 1082, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1094, 1095, 1097, 1098, 1099, 1100, 1102, 1104, 1106, 1108, 1110, 1113, 1115, 1118, 1121, 1123, 1124, 1128, 1130, 1131, 1136, 1141, 1142, 1143, 1152, 1153, 2052, 2068, 2070, 2074, 2080, 2110, 2092, 5146, 131, 4096, 2108, 1169, 15372, 4096, 4096, 1107, 146, 4096, 1033, 4096, 52
pause