/* Copyright (c) 2025 Elbitin
 *
 * This file is part of RAAS Client.
 *
 * RAAS Client is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * RAAS Client is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with RAAS Client. If not, see <https://www.gnu.org/licenses/>.
 */
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elbitin.Applications.RAAS.RAASClient.RDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elbitin.Applications.RAAS.RAASClient.RDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDP authentication:.
        /// </summary>
        internal static string General_RDPAuthenticationLabel {
            get {
                return ResourceManager.GetString("General_RDPAuthenticationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width and height need to be inteders.
        /// </summary>
        internal static string Input_WrongSizeMessage {
            get {
                return ResourceManager.GetString("Input_WrongSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string Input_WrongSizeMessageTitle {
            get {
                return ResourceManager.GetString("Input_WrongSizeMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string MainForm_ApplyButton {
            get {
                return ResourceManager.GetString("MainForm_ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MainForm_CancelButton {
            get {
                return ResourceManager.GetString("MainForm_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string MainForm_ConnectButton {
            get {
                return ResourceManager.GetString("MainForm_ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop.
        /// </summary>
        internal static string MainForm_MainFormTitle {
            get {
                return ResourceManager.GetString("MainForm_MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        internal static string MainForm_ServerLabel {
            get {
                return ResourceManager.GetString("MainForm_ServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainForm_SettingsGroupBox {
            get {
                return ResourceManager.GetString("MainForm_SettingsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote desktop error.
        /// </summary>
        internal static string Program_ErrorMessageTitle {
            get {
                return ResourceManager.GetString("Program_ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to {0}.
        /// </summary>
        internal static string RemoteDesktop_ConnectionFailedMessage {
            get {
                return ResourceManager.GetString("RemoteDesktop_ConnectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occured for {0}.
        /// </summary>
        internal static string RemoteDesktop_FatalErrorMessage {
            get {
                return ResourceManager.GetString("RemoteDesktop_FatalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not log in to {0}.
        /// </summary>
        internal static string RemoteDesktop_LoginFailedMessage {
            get {
                return ResourceManager.GetString("RemoteDesktop_LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop - {0}.
        /// </summary>
        internal static string RemoteDesktopForm_RemoteDesktopFormTitle {
            get {
                return ResourceManager.GetString("RemoteDesktopForm_RemoteDesktopFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load remote desktop settings for {0}.
        /// </summary>
        internal static string RemoteDesktopSettings_ServerLoadFailedMessage {
            get {
                return ResourceManager.GetString("RemoteDesktopSettings_ServerLoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update server settings.
        /// </summary>
        internal static string RemoteDesktopSettings_UpdateFailedMessage {
            get {
                return ResourceManager.GetString("RemoteDesktopSettings_UpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server &quot;{0}&quot; has been removed.
        /// </summary>
        internal static string Server_RemovedMessage {
            get {
                return ResourceManager.GetString("Server_RemovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load server settings.
        /// </summary>
        internal static string ServerSettings_LoadFailedMessage {
            get {
                return ResourceManager.GetString("ServerSettings_LoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load server settings for {0}.
        /// </summary>
        internal static string ServerSettings_ServerLoadFailedMessage {
            get {
                return ResourceManager.GetString("ServerSettings_ServerLoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on all monitors.
        /// </summary>
        internal static string Settings_AllMonitorsCheckbox {
            get {
                return ResourceManager.GetString("Settings_AllMonitorsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server authentication required.
        /// </summary>
        internal static string Settings_AuthenticationRequiredOption {
            get {
                return ResourceManager.GetString("Settings_AuthenticationRequiredOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning on failed server authentication.
        /// </summary>
        internal static string Settings_AuthenticationWarningOption {
            get {
                return ResourceManager.GetString("Settings_AuthenticationWarningOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection bar.
        /// </summary>
        internal static string Settings_ConnectionBarCheckbox {
            get {
                return ResourceManager.GetString("Settings_ConnectionBarCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        internal static string Settings_FullscreenCheckBox {
            get {
                return ResourceManager.GetString("Settings_FullscreenCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop height need to be an integer.
        /// </summary>
        internal static string Settings_HeightErrorInfo {
            get {
                return ResourceManager.GetString("Settings_HeightErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop height:.
        /// </summary>
        internal static string Settings_HeightLabel {
            get {
                return ResourceManager.GetString("Settings_HeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin connection bar.
        /// </summary>
        internal static string Settings_PinConnectionBarCheckbox {
            get {
                return ResourceManager.GetString("Settings_PinConnectionBarCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect clipboard.
        /// </summary>
        internal static string Settings_RedirectClipboardCheckBox {
            get {
                return ResourceManager.GetString("Settings_RedirectClipboardCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect devices.
        /// </summary>
        internal static string Settings_RedirectDevicesCheckBox {
            get {
                return ResourceManager.GetString("Settings_RedirectDevicesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect printers.
        /// </summary>
        internal static string Settings_RedirectPrintersCheckBox {
            get {
                return ResourceManager.GetString("Settings_RedirectPrintersCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes, do you wish to save?.
        /// </summary>
        internal static string Settings_UnsavedChangesMessage {
            get {
                return ResourceManager.GetString("Settings_UnsavedChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        internal static string Settings_UnsavedChangesMessageTitle {
            get {
                return ResourceManager.GetString("Settings_UnsavedChangesMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update remote desktopsettings.
        /// </summary>
        internal static string Settings_UpdateFailedMessage {
            get {
                return ResourceManager.GetString("Settings_UpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop width need to be an integer.
        /// </summary>
        internal static string Settings_WidthErrorInfo {
            get {
                return ResourceManager.GetString("Settings_WidthErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop width:.
        /// </summary>
        internal static string Settings_WidthLabel {
            get {
                return ResourceManager.GetString("Settings_WidthLabel", resourceCulture);
            }
        }
    }
}
