//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elbitin.Applications.RAAS.RAASClient.RemoteSc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resourcesso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourcesso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elbitin.Applications.RAAS.RAASClient.RemoteSc.Properties.Resourcesso", typeof(Resourcesso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macmiilka RAAS Abuur Khalad Jidka Fog ee Gaaban.
        /// </summary>
        internal static string Program_ErrorMessageTitle {
            get {
                return ResourceManager.GetString("Program_ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khalad abuurista jid-gaaban: Waa la diiday.
        /// </summary>
        internal static string Shortcut_AccessDeniedMessage {
            get {
                return ResourceManager.GetString("Shortcut_AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khalad abuuritaanka jid gaaban: {0}.
        /// </summary>
        internal static string Shortcut_ExceptionMessage {
            get {
                return ResourceManager.GetString("Shortcut_ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aan awoodin in uu abuuro jid gaaban.
        /// </summary>
        internal static string Shortcut_FailGeneralMessage {
            get {
                return ResourceManager.GetString("Shortcut_FailGeneralMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martigeliyaha looma damin {0} ahaan.
        /// </summary>
        internal static string Shortcut_NotEnabledMessage {
            get {
                return ResourceManager.GetString("Shortcut_NotEnabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aan awoodin in uu abuuro jid-gaab: Gelitaan aan la ogolayn.
        /// </summary>
        internal static string Shortcut_UnauthorizedMessage {
            get {
                return ResourceManager.GetString("Shortcut_UnauthorizedMessage", resourceCulture);
            }
        }
    }
}
