/* Copyright (c) 2025 Elbitin
 *
 * This file is part of RAAS Client.
 *
 * RAAS Client is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * RAAS Client is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with RAAS Client. If not, see <https://www.gnu.org/licenses/>.
 */
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elbitin.Applications.RAAS.RAASClient.ServerCfg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elbitin.Applications.RAAS.RAASClient.ServerCfg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following characters are not allowed for alias: &apos;.*[]()?|&lt;&gt;\\/:&quot;.
        /// </summary>
        internal static string Alias_AllowedCharactersToolTip {
            get {
                return ResourceManager.GetString("Alias_AllowedCharactersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} characters allowed for alias.
        /// </summary>
        internal static string Alias_MaximumCharactersToolTip {
            get {
                return ResourceManager.GetString("Alias_MaximumCharactersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Connection_AvailableLabel {
            get {
                return ResourceManager.GetString("Connection_AvailableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connection_ConnectButton {
            get {
                return ResourceManager.GetString("Connection_ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connection_ConnectedLabel {
            get {
                return ResourceManager.GetString("Connection_ConnectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Connection_ContactLabel {
            get {
                return ResourceManager.GetString("Connection_ContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Connection_DisconnectButton {
            get {
                return ResourceManager.GetString("Connection_DisconnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contact.
        /// </summary>
        internal static string Connection_NoContactLabel {
            get {
                return ResourceManager.GetString("Connection_NoContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server selected.
        /// </summary>
        internal static string Connection_NoServerLabel {
            get {
                return ResourceManager.GetString("Connection_NoServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAAS Client not responding.
        /// </summary>
        internal static string Connection_RAASClientNotRespondingLabel {
            get {
                return ResourceManager.GetString("Connection_RAASClientNotRespondingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        internal static string Connection_ReconnectButton {
            get {
                return ResourceManager.GetString("Connection_ReconnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAAS Server Connection.
        /// </summary>
        internal static string Connection_ServerConnectionGroupBox {
            get {
                return ResourceManager.GetString("Connection_ServerConnectionGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAAS Server version:.
        /// </summary>
        internal static string Connection_ServerVersionLabel {
            get {
                return ResourceManager.GetString("Connection_ServerVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Connection_StatusLabel {
            get {
                return ResourceManager.GetString("Connection_StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Objects.
        /// </summary>
        internal static string ExplorerExtension_3DObjectsCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_3DObjectsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD drives.
        /// </summary>
        internal static string ExplorerExtension_CDDrivesCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_CDDrivesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string ExplorerExtension_ContactsCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_ContactsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string ExplorerExtension_DesktopCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_DesktopCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible Devices and Drives.
        /// </summary>
        internal static string ExplorerExtension_DevicesAndDrivesGroupBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_DevicesAndDrivesGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string ExplorerExtension_DocumentsCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_DocumentsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string ExplorerExtension_DownloadsCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_DownloadsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable in explorer extension.
        /// </summary>
        internal static string ExplorerExtension_EnableExplorerExtensionCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_EnableExplorerExtensionCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Extension.
        /// </summary>
        internal static string ExplorerExtension_ExplorerExtensionTab {
            get {
                return ResourceManager.GetString("ExplorerExtension_ExplorerExtensionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string ExplorerExtension_FavoritesCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_FavoritesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floppy disk drives.
        /// </summary>
        internal static string ExplorerExtension_FloppyDiskDrivesCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_FloppyDiskDrivesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard drives.
        /// </summary>
        internal static string ExplorerExtension_HardDrivesCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_HardDrivesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string ExplorerExtension_LinksCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_LinksCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string ExplorerExtension_MusicCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_MusicCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string ExplorerExtension_PicturesCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_PicturesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable drives.
        /// </summary>
        internal static string ExplorerExtension_RemovableDrivesCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_RemovableDrivesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Games.
        /// </summary>
        internal static string ExplorerExtension_SavedGamesCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_SavedGamesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches.
        /// </summary>
        internal static string ExplorerExtension_SearchesCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_SearchesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string ExplorerExtension_VideosCheckBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_VideosCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible Folders.
        /// </summary>
        internal static string ExplorerExtension_VisibleFoldersGroupBox {
            get {
                return ResourceManager.GetString("ExplorerExtension_VisibleFoldersGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save explorer extension configuration.
        /// </summary>
        internal static string ExplorerSettings_SaveFailedMessage {
            get {
                return ResourceManager.GetString("ExplorerSettings_SaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load explorer extension settings for {0}.
        /// </summary>
        internal static string ExplorerSettings_ServerLoadFailedMessage {
            get {
                return ResourceManager.GetString("ExplorerSettings_ServerLoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account:.
        /// </summary>
        internal static string General_AccountLabel {
            get {
                return ResourceManager.GetString("General_AccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias:.
        /// </summary>
        internal static string General_AliasLabel {
            get {
                return ResourceManager.GetString("General_AliasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server authentication required.
        /// </summary>
        internal static string General_AuthenticationRequiredOption {
            get {
                return ResourceManager.GetString("General_AuthenticationRequiredOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning on failed server authentication.
        /// </summary>
        internal static string General_AuthenticationWarningOption {
            get {
                return ResourceManager.GetString("General_AuthenticationWarningOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto reconnect.
        /// </summary>
        internal static string General_AutoReconnectCheckBox {
            get {
                return ResourceManager.GetString("General_AutoReconnectCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart startup programs.
        /// </summary>
        internal static string General_AutoStartProgramsCheckBox {
            get {
                return ResourceManager.GetString("General_AutoStartProgramsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain:.
        /// </summary>
        internal static string General_DomainLabel {
            get {
                return ResourceManager.GetString("General_DomainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable server.
        /// </summary>
        internal static string General_EnableServerCheckBox {
            get {
                return ResourceManager.GetString("General_EnableServerCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General_GeneralTab {
            get {
                return ResourceManager.GetString("General_GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep alive agent.
        /// </summary>
        internal static string General_KeepAliveAgentCheckBox {
            get {
                return ResourceManager.GetString("General_KeepAliveAgentCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string General_PasswordLabel {
            get {
                return ResourceManager.GetString("General_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDP authentication:.
        /// </summary>
        internal static string General_RDPAuthenticationLabel {
            get {
                return ResourceManager.GetString("General_RDPAuthenticationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect clipboard.
        /// </summary>
        internal static string General_RedirectClipboardCheckBox {
            get {
                return ResourceManager.GetString("General_RedirectClipboardCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect devices.
        /// </summary>
        internal static string General_RedirectDevicesCheckBox {
            get {
                return ResourceManager.GetString("General_RedirectDevicesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect printers.
        /// </summary>
        internal static string General_RedirectPrintersCheckBox {
            get {
                return ResourceManager.GetString("General_RedirectPrintersCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string General_SettingsGroupBox {
            get {
                return ResourceManager.GetString("General_SettingsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notifications.
        /// </summary>
        internal static string General_ShowNotificationsCheckBox {
            get {
                return ResourceManager.GetString("General_ShowNotificationsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following characters are not allowed for host name: &apos;.*[]()?|&lt;&gt;\\/:&quot;.
        /// </summary>
        internal static string HostName_AllowedCharactersToolTip {
            get {
                return ResourceManager.GetString("HostName_AllowedCharactersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Hostname or IP for a RAAS Server.
        /// </summary>
        internal static string HostName_EnterHostNameMessage {
            get {
                return ResourceManager.GetString("HostName_EnterHostNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} characters allowed for host name.
        /// </summary>
        internal static string HostName_MaximumCharactersToolTip {
            get {
                return ResourceManager.GetString("HostName_MaximumCharactersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string HostNameForm_AddButton {
            get {
                return ResourceManager.GetString("HostNameForm_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string HostNameForm_CancelButton {
            get {
                return ResourceManager.GetString("HostNameForm_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add RAAS Server.
        /// </summary>
        internal static string HostNameForm_HostNameFormTitle {
            get {
                return ResourceManager.GetString("HostNameForm_HostNameFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname or IP:.
        /// </summary>
        internal static string HostNameForm_HostNameLabel {
            get {
                return ResourceManager.GetString("HostNameForm_HostNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is required for an enabled server.
        /// </summary>
        internal static string Input_AccountRequiredErrorInfo {
            get {
                return ResourceManager.GetString("Input_AccountRequiredErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias is required for an enabled server.
        /// </summary>
        internal static string Input_AliasRequiredErrorInfo {
            get {
                return ResourceManager.GetString("Input_AliasRequiredErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias is too long, max {0} characters.
        /// </summary>
        internal static string Input_AliasTooLongErrorInfo {
            get {
                return ResourceManager.GetString("Input_AliasTooLongErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias, account and password are required for an enabled server.
        /// </summary>
        internal static string Input_MissingInformationMessage {
            get {
                return ResourceManager.GetString("Input_MissingInformationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing information.
        /// </summary>
        internal static string Input_MissingInformationMessageTitle {
            get {
                return ResourceManager.GetString("Input_MissingInformationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required for an enabled server.
        /// </summary>
        internal static string Input_PasswordRequiredErrorInfo {
            get {
                return ResourceManager.GetString("Input_PasswordRequiredErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        internal static string MainForm_AddButton {
            get {
                return ResourceManager.GetString("MainForm_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string MainForm_ApplyButton {
            get {
                return ResourceManager.GetString("MainForm_ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MainForm_CancelButton {
            get {
                return ResourceManager.GetString("MainForm_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAAS Server Configuration.
        /// </summary>
        internal static string MainForm_MainFormTitle {
            get {
                return ResourceManager.GetString("MainForm_MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MainForm_OkButton {
            get {
                return ResourceManager.GetString("MainForm_OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string MainForm_RemoveButton {
            get {
                return ResourceManager.GetString("MainForm_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        internal static string MainForm_ServerLabel {
            get {
                return ResourceManager.GetString("MainForm_ServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAAS Server Configuration error.
        /// </summary>
        internal static string Program_ErrorMessageTitle {
            get {
                return ResourceManager.GetString("Program_ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append server alias to shortcut names.
        /// </summary>
        internal static string RemoteShortcuts_AppendAliasCheckBox {
            get {
                return ResourceManager.GetString("RemoteShortcuts_AppendAliasCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create desktop shortcuts.
        /// </summary>
        internal static string RemoteShortcuts_DesktopCheckBox {
            get {
                return ResourceManager.GetString("RemoteShortcuts_DesktopCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place desktop shortcuts on desktop root.
        /// </summary>
        internal static string RemoteShortcuts_DesktopRootCheckBox {
            get {
                return ResourceManager.GetString("RemoteShortcuts_DesktopRootCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable remote shortcuts.
        /// </summary>
        internal static string RemoteShortcuts_EnableRemoteShortcutsCheckBox {
            get {
                return ResourceManager.GetString("RemoteShortcuts_EnableRemoteShortcutsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server language for shortcut names.
        /// </summary>
        internal static string RemoteShortcuts_LocalizeShortcutsCheckBox {
            get {
                return ResourceManager.GetString("RemoteShortcuts_LocalizeShortcutsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Shortcuts Settings.
        /// </summary>
        internal static string RemoteShortcuts_RemoteShortcutsSettingsGroupBox {
            get {
                return ResourceManager.GetString("RemoteShortcuts_RemoteShortcutsSettingsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Shortcuts.
        /// </summary>
        internal static string RemoteShortcuts_RemoteShortcutsTab {
            get {
                return ResourceManager.GetString("RemoteShortcuts_RemoteShortcutsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create start-menu shortcuts.
        /// </summary>
        internal static string RemoteShortcuts_StartMenuCheckBox {
            get {
                return ResourceManager.GetString("RemoteShortcuts_StartMenuCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Windows App shortcuts.
        /// </summary>
        internal static string RemoteShortcuts_UWPApplicationCheckBox {
            get {
                return ResourceManager.GetString("RemoteShortcuts_UWPApplicationCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the server &quot;{0}&quot;? All its settings will be removed.
        /// </summary>
        internal static string Server_ConfirmRemoveMessage {
            get {
                return ResourceManager.GetString("Server_ConfirmRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove server.
        /// </summary>
        internal static string Server_ConfirmRemoveMessageTitle {
            get {
                return ResourceManager.GetString("Server_ConfirmRemoveMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server &quot;{0}&quot; is not configured as a RAAS Server, do you wish to add it?.
        /// </summary>
        internal static string Server_NotConfiguredMessage {
            get {
                return ResourceManager.GetString("Server_NotConfiguredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not configigured.
        /// </summary>
        internal static string Server_NotConfiguredMessageTitle {
            get {
                return ResourceManager.GetString("Server_NotConfiguredMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server &quot;{0}&quot; has been removed.
        /// </summary>
        internal static string Server_RemovedMessage {
            get {
                return ResourceManager.GetString("Server_RemovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias already occupied by a different server, please choose a different alias.
        /// </summary>
        internal static string ServerSettings_AliasOccupiedErrorInfo {
            get {
                return ResourceManager.GetString("ServerSettings_AliasOccupiedErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update server settings, alias already occupied by a different server, please choose a different alias.
        /// </summary>
        internal static string ServerSettings_AliasOccupiedMessage {
            get {
                return ResourceManager.GetString("ServerSettings_AliasOccupiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load server settings.
        /// </summary>
        internal static string ServerSettings_LoadFailedMessage {
            get {
                return ResourceManager.GetString("ServerSettings_LoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reconnect is required for settings to take effect, reconnect now?.
        /// </summary>
        internal static string ServerSettings_ReconnectRequiredMessage {
            get {
                return ResourceManager.GetString("ServerSettings_ReconnectRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server settings have changed.
        /// </summary>
        internal static string ServerSettings_ReconnectRequiredMessageTitle {
            get {
                return ResourceManager.GetString("ServerSettings_ReconnectRequiredMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save server configuration, alias already occupied by a different server, please choose a different alias.
        /// </summary>
        internal static string ServerSettings_SaveFailedAliasOccupiedMessage {
            get {
                return ResourceManager.GetString("ServerSettings_SaveFailedAliasOccupiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load server settings for {0}.
        /// </summary>
        internal static string ServerSettings_ServerLoadFailedMessage {
            get {
                return ResourceManager.GetString("ServerSettings_ServerLoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update server settings.
        /// </summary>
        internal static string ServerSettings_UpdateFailedMessage {
            get {
                return ResourceManager.GetString("ServerSettings_UpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server &quot;{0}&quot; is already configured, select existing configuration?.
        /// </summary>
        internal static string Settings_AlreadyConfiguredMessage {
            get {
                return ResourceManager.GetString("Settings_AlreadyConfiguredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server already configured.
        /// </summary>
        internal static string Settings_AlreadyConfiguredMessageTitle {
            get {
                return ResourceManager.GetString("Settings_AlreadyConfiguredMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes, do you wish to save?.
        /// </summary>
        internal static string Settings_UnsavedChangesMessage {
            get {
                return ResourceManager.GetString("Settings_UnsavedChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        internal static string Settings_UnsavedChangesMessageTitle {
            get {
                return ResourceManager.GetString("Settings_UnsavedChangesMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection bar.
        /// </summary>
        internal static string Visualizations_ConnectionBarCheckBox {
            get {
                return ResourceManager.GetString("Visualizations_ConnectionBarCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection bar opacity:.
        /// </summary>
        internal static string Visualizations_ConnectionBarOpacityLabel {
            get {
                return ResourceManager.GetString("Visualizations_ConnectionBarOpacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosslines.
        /// </summary>
        internal static string Visualizations_CrossLinesCheckBox {
            get {
                return ResourceManager.GetString("Visualizations_CrossLinesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable visualizations.
        /// </summary>
        internal static string Visualizations_EnableVisualizationsCheckBox {
            get {
                return ResourceManager.GetString("Visualizations_EnableVisualizationsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        internal static string Visualizations_FramesCheckBox {
            get {
                return ResourceManager.GetString("Visualizations_FramesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line color.
        /// </summary>
        internal static string Visualizations_LineColorButton {
            get {
                return ResourceManager.GetString("Visualizations_LineColorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main color.
        /// </summary>
        internal static string Visualizations_MainColorButton {
            get {
                return ResourceManager.GetString("Visualizations_MainColorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay opacity:.
        /// </summary>
        internal static string Visualizations_OverlayOpacityLabel {
            get {
                return ResourceManager.GetString("Visualizations_OverlayOpacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlays when inactive.
        /// </summary>
        internal static string Visualizations_OverlaysCheckBox {
            get {
                return ResourceManager.GetString("Visualizations_OverlaysCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        internal static string Visualizations_TextColorButton {
            get {
                return ResourceManager.GetString("Visualizations_TextColorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizations Settings.
        /// </summary>
        internal static string Visualizations_VisualizationsGroupBox {
            get {
                return ResourceManager.GetString("Visualizations_VisualizationsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizations.
        /// </summary>
        internal static string Visualizations_VisualizationsTab {
            get {
                return ResourceManager.GetString("Visualizations_VisualizationsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save visualizations configuration.
        /// </summary>
        internal static string VisualizationsSettings_SaveFailedMessage {
            get {
                return ResourceManager.GetString("VisualizationsSettings_SaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load visualizations settings for {0}.
        /// </summary>
        internal static string VisualizationsSettings_ServerLoadFailedMessage {
            get {
                return ResourceManager.GetString("VisualizationsSettings_ServerLoadFailedMessage", resourceCulture);
            }
        }
    }
}
